[package]
name = "planetext"
version = "0.1.0"
description = "数式を記法を意識せずに書けるテキストエディタ"
authors = ["Motoyuki-Oya"]
edition = "2021"

[lib]
# `_lib` サフィックスは冗長に見えるかもしれませんが、lib 名を一意にし、bin 名と競合しないようにする必要があります。これは Windows のみの問題のようです。https://github.com/rust-lang/cargo/issues/8519 を参照してください。
name = "planetext_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
planetext-document = { path = "../crates/planetext-document" }
tauri = { version = "2", features = ["tray-icon", "image-png", "image-ico"] }

tauri-plugin-dialog = "2"
serde_json = "1"
arboard = { version = "3.6.1", default-features = false, features = ["windows-sys"] }
tauri-plugin-single-instance = "2"
tauri-plugin-global-shortcut = "2"
tokio = { version = "1", features = ["time"] }
