//! 言語定義（LanguageDef）のデータ構造および組み込み言語定義。

use std::collections::HashSet;

/// 言語ごとの構文定義。
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LanguageDef {
    pub name: String,
    pub extensions: Vec<String>,
    pub line_comments: Vec<String>,
    pub block_comments: Vec<(String, String)>,
    pub string_delimiters: Vec<String>,
    pub keywords: HashSet<String>,
    pub types: HashSet<String>,
    pub builtins: HashSet<String>,
    pub constants: HashSet<String>,
    pub operators: HashSet<String>,
}

impl LanguageDef {
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            extensions: Vec::new(),
            line_comments: Vec::new(),
            block_comments: Vec::new(),
            string_delimiters: Vec::new(),
            keywords: HashSet::new(),
            types: HashSet::new(),
            builtins: HashSet::new(),
            constants: HashSet::new(),
            operators: HashSet::new(),
        }
    }
}

/// 組み込みの 10 言語定義を生成します。
pub fn built_in_languages() -> Vec<LanguageDef> {
    vec![
        rust_def(),
        kotlin_def(),
        typescript_def(),
        javascript_def(),
        python_def(),
        toml_def(),
        json_def(),
        html_def(),
        css_def(),
        markdown_def(),
        latex_def(),
    ]
}

fn to_set(items: &[&str]) -> HashSet<String> {
    items.iter().map(|s| s.to_string()).collect()
}

fn rust_def() -> LanguageDef {
    LanguageDef {
        name: "Rust".into(),
        extensions: vec!["rs".into()],
        line_comments: vec!["//".into()],
        block_comments: vec![("/*".into(), "*/".into())],
        string_delimiters: vec!["\"".into(), "r#\"".into()],
        keywords: to_set(&[
            "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
            "extern", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
            "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super", "trait",
            "type", "unsafe", "use", "where", "while", "yield",
        ]),
        types: to_set(&[
            "bool", "char", "str", "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32",
            "i64", "i128", "isize", "f32", "f64", "String", "Vec", "Option", "Result", "Box", "Rc",
            "Arc", "RefCell", "Mutex",
        ]),
        builtins: to_set(&[
            "println",
            "eprintln",
            "print",
            "eprint",
            "format",
            "vec",
            "panic",
            "assert",
            "assert_eq",
            "assert_ne",
            "todo",
            "unimplemented",
            "unreachable",
            "dbg",
        ]),
        constants: to_set(&["true", "false", "Some", "None", "Ok", "Err"]),
        operators: to_set(&[
            "+", "-", "*", "/", "%", "=", "==", "!=", "<", ">", "<=", ">=", "&&", "||", "!", "&",
            "|", "^", "<<", ">>", "=>", "->", "::",
        ]),
    }
}

fn kotlin_def() -> LanguageDef {
    LanguageDef {
        name: "Kotlin".into(),
        extensions: vec!["kt".into(), "kts".into()],
        line_comments: vec!["//".into()],
        block_comments: vec![("/*".into(), "*/".into())],
        string_delimiters: vec!["\"".into(), "\"\"\"".into()],
        keywords: to_set(&[
            "package",
            "import",
            "class",
            "interface",
            "fun",
            "val",
            "var",
            "public",
            "private",
            "protected",
            "internal",
            "override",
            "suspend",
            "data",
            "sealed",
            "enum",
            "object",
            "companion",
            "return",
            "if",
            "else",
            "when",
            "for",
            "while",
            "do",
            "try",
            "catch",
            "finally",
            "throw",
            "is",
            "in",
            "by",
            "lazy",
            "abstract",
            "open",
            "final",
            "lateinit",
            "vararg",
            "inline",
            "crossinline",
            "noinline",
            "tailrec",
            "operator",
            "infix",
            "const",
            "typealias",
        ]),
        types: to_set(&[
            "Int",
            "Long",
            "Short",
            "Byte",
            "Double",
            "Float",
            "Boolean",
            "String",
            "Char",
            "List",
            "MutableList",
            "Map",
            "MutableMap",
            "Set",
            "MutableSet",
            "Array",
            "Unit",
            "Any",
            "Nothing",
        ]),
        builtins: to_set(&["println", "print", "require", "check", "error", "lazy"]),
        constants: to_set(&["true", "false", "null", "this", "super"]),
        operators: to_set(&[
            "+", "-", "*", "/", "%", "=", "==", "!=", "===", "!==", "<", ">", "<=", ">=", "&&",
            "||", "!", "?.", "?:", "!!", "->", "::",
        ]),
    }
}

fn typescript_def() -> LanguageDef {
    let mut def = javascript_def();
    def.name = "TypeScript".into();
    def.extensions = vec!["ts".into(), "tsx".into(), "mts".into(), "cts".into()];
    def.keywords.extend(
        [
            "interface",
            "type",
            "namespace",
            "declare",
            "enum",
            "implements",
            "readonly",
            "as",
            "is",
            "keyof",
            "typeof",
            "never",
            "unknown",
            "any",
            "override",
            "abstract",
            "satisfies",
        ]
        .iter()
        .map(|s| s.to_string()),
    );
    def.types.extend(
        [
            "string", "number", "boolean", "symbol", "bigint", "void", "object", "Promise",
            "Array", "Record", "Partial", "Required", "Readonly",
        ]
        .iter()
        .map(|s| s.to_string()),
    );
    def
}

fn javascript_def() -> LanguageDef {
    LanguageDef {
        name: "JavaScript".into(),
        extensions: vec!["js".into(), "jsx".into(), "mjs".into(), "cjs".into()],
        line_comments: vec!["//".into()],
        block_comments: vec![("/*".into(), "*/".into())],
        string_delimiters: vec!["\"".into(), "'".into(), "`".into()],
        keywords: to_set(&[
            "async",
            "await",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "export",
            "extends",
            "finally",
            "for",
            "function",
            "if",
            "import",
            "in",
            "instanceof",
            "let",
            "new",
            "return",
            "static",
            "super",
            "switch",
            "this",
            "throw",
            "try",
            "typeof",
            "var",
            "void",
            "while",
            "with",
            "yield",
            "from",
            "of",
        ]),
        types: to_set(&[
            "Object", "Function", "Boolean", "Symbol", "Number", "BigInt", "Math", "Date",
            "String", "RegExp", "Array", "Map", "Set", "WeakMap", "WeakSet", "Promise",
        ]),
        builtins: to_set(&[
            "console",
            "window",
            "document",
            "parseInt",
            "parseFloat",
            "isNaN",
            "isFinite",
            "setTimeout",
            "setInterval",
            "clearTimeout",
            "clearInterval",
        ]),
        constants: to_set(&["true", "false", "null", "undefined", "NaN", "Infinity"]),
        operators: to_set(&[
            "+", "-", "*", "/", "%", "=", "==", "===", "!=", "!==", "<", ">", "<=", ">=", "&&",
            "||", "!", "??", "?.", "=>", "++", "--", "+=", "-=", "*=", "/=",
        ]),
    }
}

fn python_def() -> LanguageDef {
    LanguageDef {
        name: "Python".into(),
        extensions: vec!["py".into(), "pyw".into(), "pyi".into()],
        line_comments: vec!["#".into()],
        block_comments: vec![
            ("'''".into(), "'''".into()),
            ("\"\"\"".into(), "\"\"\"".into()),
        ],
        string_delimiters: vec!["\"".into(), "'".into(), "\"\"\"".into(), "'''".into()],
        keywords: to_set(&[
            "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del",
            "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in",
            "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
            "with", "yield", "match", "case",
        ]),
        types: to_set(&[
            "int",
            "float",
            "complex",
            "str",
            "bytes",
            "bytearray",
            "memoryview",
            "list",
            "tuple",
            "range",
            "dict",
            "set",
            "frozenset",
            "bool",
            "type",
            "Optional",
            "Union",
            "List",
            "Dict",
            "Tuple",
            "Set",
            "Any",
        ]),
        builtins: to_set(&[
            "print",
            "len",
            "range",
            "enumerate",
            "zip",
            "map",
            "filter",
            "sorted",
            "reversed",
            "sum",
            "min",
            "max",
            "abs",
            "round",
            "all",
            "any",
            "isinstance",
            "issubclass",
            "getattr",
            "setattr",
            "hasattr",
            "open",
            "input",
        ]),
        constants: to_set(&["True", "False", "None", "self", "cls"]),
        operators: to_set(&[
            "+", "-", "*", "/", "//", "%", "**", "=", "==", "!=", "<", ">", "<=", ">=", "->", "+=",
            "-=", "*=", "/=",
        ]),
    }
}

fn toml_def() -> LanguageDef {
    LanguageDef {
        name: "TOML".into(),
        extensions: vec!["toml".into()],
        line_comments: vec!["#".into()],
        block_comments: Vec::new(),
        string_delimiters: vec!["\"".into(), "'".into(), "\"\"\"".into(), "'''".into()],
        keywords: HashSet::new(),
        types: HashSet::new(),
        builtins: HashSet::new(),
        constants: to_set(&["true", "false", "nan", "inf"]),
        operators: to_set(&["="]),
    }
}

fn json_def() -> LanguageDef {
    LanguageDef {
        name: "JSON".into(),
        extensions: vec!["json".into(), "jsonc".into()],
        line_comments: vec!["//".into()],
        block_comments: vec![("/*".into(), "*/".into())],
        string_delimiters: vec!["\"".into()],
        keywords: HashSet::new(),
        types: HashSet::new(),
        builtins: HashSet::new(),
        constants: to_set(&["true", "false", "null"]),
        operators: to_set(&[":", ","]),
    }
}

fn html_def() -> LanguageDef {
    LanguageDef {
        name: "HTML".into(),
        extensions: vec!["html".into(), "htm".into(), "svg".into()],
        line_comments: Vec::new(),
        block_comments: vec![("<!--".into(), "-->".into())],
        string_delimiters: vec!["\"".into(), "'".into()],
        keywords: to_set(&[
            "doctype", "html", "head", "body", "title", "meta", "link", "script", "style", "div",
            "span", "p", "a", "img", "ul", "ol", "li", "table", "tr", "td", "th", "form", "input",
            "button", "textarea", "select", "option", "h1", "h2", "h3", "h4", "h5", "h6", "header",
            "footer", "nav", "section", "article", "main",
        ]),
        types: HashSet::new(),
        builtins: to_set(&[
            "class",
            "id",
            "style",
            "src",
            "href",
            "type",
            "name",
            "value",
            "placeholder",
            "alt",
            "title",
            "rel",
            "target",
            "width",
            "height",
            "disabled",
            "checked",
            "readonly",
        ]),
        constants: HashSet::new(),
        operators: to_set(&["<", ">", "</", "/>", "="]),
    }
}

fn css_def() -> LanguageDef {
    LanguageDef {
        name: "CSS".into(),
        extensions: vec!["css".into(), "scss".into(), "less".into()],
        line_comments: vec!["//".into()],
        block_comments: vec![("/*".into(), "*/".into())],
        string_delimiters: vec!["\"".into(), "'".into()],
        keywords: to_set(&[
            "@import",
            "@media",
            "@keyframes",
            "@font-face",
            "@supports",
            "@charset",
            "important",
            "from",
            "to",
        ]),
        types: to_set(&[
            "px", "em", "rem", "vh", "vw", "%", "deg", "s", "ms", "fr", "auto", "none", "inherit",
            "initial", "unset",
        ]),
        builtins: to_set(&[
            "var",
            "calc",
            "rgb",
            "rgba",
            "hsl",
            "hsla",
            "color-mix",
            "linear-gradient",
            "radial-gradient",
            "url",
            "min",
            "max",
            "clamp",
        ]),
        constants: to_set(&[
            "display",
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "width",
            "height",
            "min-width",
            "max-width",
            "min-height",
            "max-height",
            "margin",
            "padding",
            "border",
            "background",
            "color",
            "font",
            "font-size",
            "font-family",
            "font-weight",
            "line-height",
            "text-align",
            "text-decoration",
            "flex",
            "grid",
            "align-items",
            "justify-content",
            "gap",
            "opacity",
            "overflow",
            "z-index",
            "cursor",
            "pointer-events",
            "user-select",
            "box-sizing",
            "border-radius",
            "box-shadow",
            "transition",
            "animation",
            "transform",
        ]),
        operators: to_set(&[":", ";", "{", "}", ",", ">", "+", "~"]),
    }
}

fn markdown_def() -> LanguageDef {
    LanguageDef {
        name: "Markdown".into(),
        extensions: vec!["md".into(), "markdown".into()],
        line_comments: Vec::new(),
        block_comments: vec![("<!--".into(), "-->".into())],
        string_delimiters: vec!["`".into(), "```".into()],
        keywords: to_set(&[
            "#", "##", "###", "####", "#####", "######", "-", "*", "+", ">",
        ]),
        types: HashSet::new(),
        builtins: HashSet::new(),
        constants: HashSet::new(),
        operators: to_set(&["[", "]", "(", ")", "!", "*", "_", "`", "|"]),
    }
}

fn latex_def() -> LanguageDef {
    LanguageDef {
        name: "LaTeX".into(),
        extensions: vec!["tex".into(), "latex".into(), "sty".into(), "cls".into()],
        line_comments: vec!["%".into()],
        block_comments: Vec::new(),
        string_delimiters: Vec::new(),
        keywords: to_set(&[
            "\\begin",
            "\\end",
            "\\documentclass",
            "\\usepackage",
            "\\section",
            "\\subsection",
            "\\subsubsection",
            "\\item",
            "\\cite",
            "\\ref",
            "\\label",
            "\\newcommand",
            "\\renewcommand",
        ]),
        types: to_set(&[
            "document",
            "equation",
            "align",
            "matrix",
            "pmatrix",
            "bmatrix",
            "cases",
            "itemize",
            "enumerate",
            "figure",
            "table",
        ]),
        builtins: to_set(&[
            "\\frac",
            "\\sqrt",
            "\\sum",
            "\\int",
            "\\prod",
            "\\lim",
            "\\alpha",
            "\\beta",
            "\\gamma",
            "\\delta",
            "\\epsilon",
            "\\theta",
            "\\lambda",
            "\\mu",
            "\\pi",
            "\\sigma",
            "\\phi",
            "\\omega",
            "\\infty",
            "\\partial",
            "\\times",
            "\\cdot",
            "\\le",
            "\\ge",
            "\\ne",
            "\\approx",
            "\\in",
            "\\subset",
            "\\cup",
            "\\cap",
            "\\text",
            "\\mathbf",
            "\\mathit",
            "\\mathbb",
            "\\mathcal",
        ]),
        constants: HashSet::new(),
        operators: to_set(&["$", "$$", "{", "}", "[", "]", "^", "_", "&", "\\\\"]),
    }
}
